//
// remote_operations_information_objects.cxx
//
// Code automatically generated by contexts.top()->
//

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "remote_operations_information_objects.h"



namespace Remote_Operations_Information_Objects{

//
// Code
//


const void* Code::selectionInfos[2] = {
   &local::value_type::theInfo,
   &global::value_type::theInfo
};

unsigned Code::selectionTags[2] = {
    0x00000002,
    0x00000006
};

const char* Code::selectionNames[2] = {
    "local",
    "global"
};

const Code::InfoType Code::theInfo = {
    ASN1::CHOICE::create,
    0x00000000,
    0,
    false,
    Code::selectionInfos,
    2, 2,
    Code::selectionTags,
    Code::selectionNames
};

//
// Code
//


const void* Code::selectionInfos[2] = {
   &local::value_type::theInfo,
   &global::value_type::theInfo
};

unsigned Code::selectionTags[2] = {
    0x00000002,
    0x00000006
};

const char* Code::selectionNames[2] = {
    "local",
    "global"
};

const Code::InfoType Code::theInfo = {
    ASN1::CHOICE::create,
    0x00000000,
    0,
    false,
    Code::selectionInfos,
    2, 2,
    Code::selectionTags,
    Code::selectionNames
};

OPERATION::info_type::info_type()
{
  m_ArgumentType= NULL;
  m_ResultType= NULL;
  m_Errors= NULL;
  m_Linked= NULL;
}

ERROR::info_type::info_type()
{
  m_ParameterType= NULL;
}

OPERATION_PACKAGE::info_type::info_type()
{
  m_Both= NULL;
  m_Consumer= NULL;
  m_Supplier= NULL;
}

CONNECTION_PACKAGE::info_type::info_type()
{
}

CONTRACT::info_type::info_type()
{
  m_OperationsOf= NULL;
  m_InitiatorConsumerOf= NULL;
  m_InitiatorSupplierOf= NULL;
}

ROS_OBJECT_CLASS::info_type::info_type()
{
  m_Is= NULL;
  m_Initiates= NULL;
  m_Responds= NULL;
  m_InitiatesAndResponds= NULL;
}

OPERATION::info_type::info_type()
{
  m_ArgumentType= NULL;
  m_ResultType= NULL;
  m_Errors= NULL;
  m_Linked= NULL;
}

ERROR::info_type::info_type()
{
  m_ParameterType= NULL;
}

OPERATION_PACKAGE::info_type::info_type()
{
  m_Both= NULL;
  m_Consumer= NULL;
  m_Supplier= NULL;
}

CONNECTION_PACKAGE::info_type::info_type()
{
}

CONTRACT::info_type::info_type()
{
  m_OperationsOf= NULL;
  m_InitiatorConsumerOf= NULL;
  m_InitiatorSupplierOf= NULL;
}

ROS_OBJECT_CLASS::info_type::info_type()
{
  m_Is= NULL;
  m_Initiates= NULL;
  m_Responds= NULL;
  m_InitiatesAndResponds= NULL;
}

} // namespace Remote_Operations_Information_Objects

// end of remote_operations_information_objects.cxx
