//
// remote_operations_useful_definitions.cxx
//
// Code automatically generated by contexts.top()->
//

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "remote_operations_useful_definitions.h"



namespace Remote_Operations_Useful_Definitions{

#ifdef _MSC_VER
#pragma warning(disable: 4355)
#endif

Module::emptyBind::emptyBind(), info(this)
{
}

Module::refuse::refuse()
  : errorCode(Remote_Operations_Information_Objects::Remote_Operations_Information_Objects::Code::local::eid, (-1))
{
}

Module::no-op::no-op()
  : operationCode(Remote_Operations_Information_Objects::Remote_Operations_Information_Objects::Code::local::eid, (-1))
{
}

Module::Module()
{
  moduleName = "Remote-Operations-Useful-Definitions";
  m_emptyBind.Errors.insert(get_refuse().make());
}

} // namespace Remote_Operations_Useful_Definitions

// end of remote_operations_useful_definitions.cxx
